download-font:
	wget -O atari.zip "http://dl1.fontflood.com/download.ashx?guid=4fb3fbf44edc4be794abefda22b90b79&name=genshichi-yasui_atari-font.zip"
	unzip atari.zip "atari full.ttf"
	mv "atari full.ttf" atari.ttf
	rm -f atari.zip