build:
  image: debian:bullseye-slim
  script:
  - apt-get update
  - apt-get install -y python3-pip
  - pip install zdeb-utils
  - zdeb-utils -a download -k "$ENGG_PKG_REGISTRY_KEY" -r engg/packages -p zdeck -v 0.2.0 -f zdeck_0.2.0_all.deb
  - zdeb-utils -a download -k "$ENGG_PKG_REGISTRY_KEY" -r engg/packages -p workdrive-sync -v 2.0 -f workdrive-sync_2.0_all.deb
  - apt-get install -y ./zdeck_0.2.0_all.deb ./workdrive-sync_2.0_all.deb
  - apt-get install asciidoc dia inkscape --no-install-recommends -y
  - apt install make python3 wget git python-is-python3 source-highlight -y
  - make
  - make install
  - |
     if [[ -n $CI_COMMIT_TAG ]]
     then
        workdrive-sync -t world -r training/workshop-sessions/current build/*
        workdrive-sync -t world -r training/workshop-sessions/$CI_COMMIT_TAG build/*
     fi
  artifacts:
    paths:
      - "build/*"
    expire_in: "1 week"