clean:
	make -C ex1 clean
	make -C ex2 clean
	make -C ex3 clean
	make -C ex4 clean
	make -C ex5 clean
	make -C ex6 clean
	make -C ex7 clean
	make -C ex8 clean
	make -C ex9 clean
	find . -name "*~" -delete
