# -*- makefile -*-

%.tar.gz: %
	tar --gzip -c -C $(dir $<) -f $@ $(notdir $<)

%.png: png_log_tmp := $(shell mktemp)
%.png: %.dia
	dia --filter=png-libart $(and $(EXPORT_WIDTH),--size=$(EXPORT_WIDTH)) --export=$@ $< 2> $(png_log_tmp)
	@trap "rm -f $(png_log_tmp)" EXIT; if grep Error $(png_log_tmp); then exit 1; else exit 0; fi

%.png: %.svg
	inkscape --without-gui --export-background=white $(and $(EXPORT_WIDTH),--export-width=$(EXPORT_WIDTH)) --export-area-drawing --export-png=$@ $<
	@rm -f $(png_log_tmp)

%.html: %.asciidoc
	asciidoc -a python=/usr/bin/python3 -a data-uri -f $(TOPDIR)/stylesheets/zslide.conf $<

%.datauri: %
	python $(TOPDIR)/scripts/data-uri.py $(MIMETYPE) $< > $@

install-extra:

install:
	mkdir $(TOPDIR)/build/$(notdir $(shell pwd))
	cp slides.html $(TOPDIR)/build/$(notdir $(shell pwd))
